### PR TITLE
Some last minute housekeeping changes

### PR DESCRIPTION
**Pull request by FlorianSong**
A few bug fixes and an updated readme

### CODE REVIEW

**Comment by stevenkbennett** [comment]
Task 1 Prediction - Density
-----------------
No results submitted for task 1

Task 2 Prediction - Centrosymmetric
-----------------
No results submitted for task 2

Task 3 Prediction - Mean Distances
-----------------
No results submitted for task 3

Task 4 Prediction - Van der Waals Contacts
-----------------
No results submitted for task 4

Bonus Task 1 Prediction - Packing Coefficient
-----------------
No results submitted for bonus task 1

Bonus Task 2 Prediction - Cell Volume
-----------------
No results submitted for bonus task 2

Bonus Task 3 Prediction - Space Group Symbol
-----------------
No results submitted for bonus task 3

__Total Points__
-----------------
0

**Comment by stevenkbennett** [comment]
Task 1 Prediction - Density
-----------------
No results submitted for task 1

Task 2 Prediction - Centrosymmetric
-----------------
No results submitted for task 2

Task 3 Prediction - Mean Distances
-----------------
No results submitted for task 3

Task 4 Prediction - Van der Waals Contacts
-----------------
No results submitted for task 4

Bonus Task 1 Prediction - Packing Coefficient
-----------------
No results submitted for bonus task 1

Bonus Task 2 Prediction - Cell Volume
-----------------
No results submitted for bonus task 2

Bonus Task 3 Prediction - Space Group Symbol
-----------------
No results submitted for bonus task 3

__Total Points__
-----------------
0

**Comment by stevenkbennett** [comment]
Task 1 Prediction - Density
-----------------
No results submitted for task 1

Task 2 Prediction - Centrosymmetric
-----------------
No results submitted for task 2

Task 3 Prediction - Mean Distances
-----------------
No results submitted for task 3

Task 4 Prediction - Van der Waals Contacts
-----------------
No results submitted for task 4

Bonus Task 1 Prediction - Packing Coefficient
-----------------
No results submitted for bonus task 1

Bonus Task 2 Prediction - Cell Volume
-----------------
No results submitted for bonus task 2

Bonus Task 3 Prediction - Space Group Symbol
-----------------
No results submitted for bonus task 3

__Total Points__
-----------------
0

**Comment by stevenkbennett** [comment]
Task 1 Prediction - Density
-----------------
No results submitted for task 1

Task 2 Prediction - Centrosymmetric
-----------------
No results submitted for task 2

Task 3 Prediction - Mean Distances
-----------------
No results submitted for task 3

Task 4 Prediction - Van der Waals Contacts
-----------------
No results submitted for task 4

Bonus Task 1 Prediction - Packing Coefficient
-----------------
No results submitted for bonus task 1

Bonus Task 2 Prediction - Cell Volume
-----------------
No results submitted for bonus task 2

Bonus Task 3 Prediction - Space Group Symbol
-----------------
No results submitted for bonus task 3

__Total Points__
-----------------
0

**Comment by FlorianSong** [comment]
I think this is working now, as expected. All numbers are correct and hopefully all bugs are squashed

**Comment by stevenkbennett** [comment]
Task 1 Prediction - Density
-----------------
No results submitted for task 1

Task 2 Prediction - Centrosymmetric
-----------------
No results submitted for task 2

Task 3 Prediction - Mean Distances
-----------------
No results submitted for task 3

Task 4 Prediction - Van der Waals Contacts
-----------------
No results submitted for task 4

Bonus Task 1 Prediction - Packing Coefficient
-----------------
No results submitted for bonus task 1

Bonus Task 2 Prediction - Cell Volume
-----------------
No results submitted for bonus task 2

Bonus Task 3 Prediction - Space Group Symbol
-----------------
No results submitted for bonus task 3

__Total Points__
-----------------
0/130

**Comment by stevenkbennett** [comment]
Task 1 Prediction - Density
-----------------
No results submitted for task 1

Task 2 Prediction - Centrosymmetric
-----------------
No results submitted for task 2

Task 3 Prediction - Mean Distances
-----------------
No results submitted for task 3

Task 4 Prediction - Van der Waals Contacts
-----------------
No results submitted for task 4

Bonus Task 1 Prediction - Packing Coefficient
-----------------
No results submitted for bonus task 1

Bonus Task 2 Prediction - Cell Volume
-----------------
No results submitted for bonus task 2

Bonus Task 3 Prediction - Space Group Symbol
-----------------
No results submitted for bonus task 3

__Total Points__
-----------------
0/130

**Review by stevenkbennett — APPROVED** [review]

**Review by stevenkbennett — APPROVED** [review]

**Pull request merged**
